### ISSUE TITLE
World save corrupted when switching to 2.10.

### ISSUE THREAD

**Issue by Furious1964** [covers1624/PowerConverters#14]
Everything was working fine and was using 2.09. I switched to 2.10 and just started to play again tonight and when I tried to load my world, the game said that it was corrupted because of a mod. Please look into this as I'm trying to recover my world.

**Comment by covers1624** [comment]
Ok.. can you be a bit more specific as to how it hapend, perhaps some screenshots of the game saying that it is corrupted and a log file wouldn't hurt, im not trying to be a dick but saying that it broke without showing me a log or something makes it really hard to fix my bugs.

**Comment by Furious1964** [comment]
I just checked my log files and can't find any reference to that. However, I was able to get an earlier version of my world back when I removed the mod and it's config files. I can replicate the problem again, but it's working now. If you want me to try, let me know.

**Comment by Furious1964** [comment]
OK, I noticed something. Is there a way to convert MJ into RF?

**Comment by covers1624** [comment]
MJ is no longer supported and is removed from build craft update your mods. Also what forge version are you using?

**Comment by Furious1964** [comment]
I'm playing FTB Infinity which is for 1.7.10 and the mods are all updated for it. It's not 1.8.x yet as those mods are not updated to that version. I use Forge 10.13.4.1448.as it came with the pack.

**Comment by covers1624** [comment]
hmm, ill run some tests when i get home and see what i come up with, this should not happen btw, it will only happen if some mod is messing with the Remapping event that i use to convert the mod id for PC.

**Comment by Furious1964** [comment]
I could test it again to see if it comes up, but will have to be during the weekend. All I can tell yo is that I went from 2.08 to 2.09 without deleting the old configs and when I upgraded to 2.10, that's when it happened.
