### ISSUE TITLE
RF Power Converters unavailable in certain mod configurations

### ISSUE THREAD

**Issue by ErikaRedmark** [covers1624/PowerConverters#15]
In a private mod pack, we have Extra Utilities (which generates RF) as well as Immersive Engineering. From my understanding, Power Converters looks for certain mods to be available to decide whether to enable the power converters to a specific power type. Unfortunately, all the mods it searches for apparently does not include these two. Would it be possible (or if it already is, please confirm) to force the system to load converters for power systems, possibly via config, even if it otherwise wouldn't detect them? Or if not that, at least add Extra Utilities/Immersive Engineering to the group of RF mods?

**Comment by ErikaRedmark** [comment]
I think I may have confused this mod with another one also called PowerConverters: the URL inside the .jar doesn't point here at all, and the source code as I see it here doesn't appear to be mod specific and is using configurations for power loading (also it is very different from what I see when I open the .jar I have). I think I'm getting a bit confused over what actual mod I'm looking at. Apologies for the error: I'll just close this issue.

**Comment by covers1624** [comment]
all good, you may be using prtablejims version of PowerConverters.
