### ISSUE TITLE
Power Converters lose charge.

### ISSUE THREAD

**Issue by Furious1964** [covers1624/PowerConverters#16]
Ran into a problem: the power converters lose charge when I leave the overworld or I left the chunk and return later. Is this a known issue and is it being looked into?

**Comment by covers1624** [comment]
Interesting.. Will look in to it now.

**Comment by Furious1964** [comment]
I'm still on FTB Infinity, the latest update.I tried attaching it to its own power lines and testing with fully drained charge. The original incident had no charge and no power flow, even though it was attached to 9 Advanced Solar Panels.

**Comment by covers1624** [comment]
I have tested this in both the ways you described and cannot reproduce it.

**Comment by Furious1964** [comment]
If it happens again, I make a screenshot.

**Comment by covers1624** [comment]
Alright, it shouldnt happen anyway i save the charge to nbt and i load it from nbt..

**Comment by Furious1964** [comment]
Here you go, the screenshots.
Taken when I had one job going: http://imageshack.com/a/img911/5093/Zz5BKn.png
How it was set up: http://imageshack.com/a/img540/6208/0YLpsJ.png
What happened when I broke the IC2 Consumer (notice the power cable still thinks there's something attached): http://imageshack.com/a/img540/6631/nFiOJh.png
And taken after the job was completed: http://imageshack.com/a/img537/4636/mD2pdW.png

Only thing I did was go to the Nether, stay there for 30 seconds and then leave.
