### ISSUE TITLE
Steam not working

### ISSUE THREAD

**Issue by Staegrin** [covers1624/PowerConverters#2]
Just doing some testing and after trying all four mods that use and produce steam none work with the latest version of steam producer and consumer.

Tried with:
Railcraft steam
Flaxbeard's steam power steam
Minefactory Reloaded steam
IC2 superheated steam and steam

Steam producer says it is producing something when power is supplied to the Energy Bridge, but nothing is actually coming out of it.

**Comment by covers1624** [comment]
This should be fixed now, will only work for normal steam, MineFactory Reloaded, RailCrft, Thermal Expansion.

**Comment by covers1624** [comment]
Build Pushed, Available on CurseForge

**Comment by Staegrin** [comment]
Yes, steam works completely now.
