### ISSUE TITLE
Config option for Update Checker.

### ISSUE THREAD

**Issue by InsaneJ** [covers1624/PowerConverters#3]
Using Power Converters 1.7.10-2.3 it mentions there is an update available upon loading a world. When I go to the provided link I'm send to the CurseForge page where the latest version is 2.3 which I'm already using.

Also would it be possible to add a config option to disable update messages in chat? If you want to check in the background to get an idea of how many people are using the mod that's fine of course. It's just that the message will get in the way at some point for people using mod packs who can't (yet) update for various reasons.

**Comment by covers1624** [comment]
yeah mt internet dropped right as i was doing an update and i had already pushed the version to git. i can certainly add a config for that, i see how that could get annoying, this will be in the next update.

**Comment by portablejim** [comment]
You can also use branches to separate the released version from the development version.

**Comment by covers1624** [comment]
True, I may have to look in to that in the future.
