### ISSUE TITLE
EU energy output problem. 1.7.10 Forge server 1614. Build 2.11

### ISSUE THREAD

**Issue by walwan** [covers1624/PowerConverters#37]
I installed Power Converter 3 in my forge server. Sometimes the EU producer went wrong. It doesn't output any energy. And the server console output a warning : "[Server thread/WARN] [IC2.EnergyNet]: EnergyNet.addTileEntity: covers1624.powerconverters.tile.ic2.TileEntityIndustrialCraftProducer@449243f5 (covers1624.powerconverters.tile.ic2.TileEntityIndustrialCraftProducer@449243f5) is still conflicting with covers1624.powerconverters.tile.ic2.TileEntityIndustrialCraftProducer@16c193e9 using the same position (overlapping), aborting " I have to restrat server to fix this. I had searched it on google. I think it's related to chunk load. But you said you had fix it on 2.11 version. What's more, in single player it works well.
The IC2 cable seems to regard the air as a energy source.
http://i.imgur.com/D3p7ACs.png
This is my server fml log and client fml log. 
[whc.zip](https://github.com/covers1624/PowerConverters/files/1224591/whc.zip)
 Thanks in advance.

**Comment by AdamDeBeers** [comment]
I have exactly same problem

it looks like problem with chunk loading, when chunk is loaded with some loader, it works 100%

if chunk is unloaded, it breaks very often

**Comment by gigabit101** [comment]
I dont think this will be fixed in such a old mc version

**Comment by covers1624** [comment]
Yeah, there may be things happening with this mod in private, but it wont be the same.
